name: Generate Snake

on:
  schedule: # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: StathisKotanidis
          outputs: dist/snake.svg

      - name: Push Snake to the output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          directory: dist
